name: publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      contents: read
      id-token: write

    steps:
      - name: -> checkout
        uses: actions/checkout@v6
        with:
          ref: main

      - name: -> setup py
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: -> setup uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: -> setup just
        uses: extractions/setup-just@v3
        with:
          just-version: '*'

      - name: -> sync
        run: just sync

      - name: -> ruff
        run: |
          uv run ruff check --fix-only .

      - name: -> pyrefly
        run: uv run pyrefly check

      - name: build pkg
        uses: ./.github/actions/build

      - name: dl build
        uses: actions/download-artifact@v5
        with:
          name: build-dist
          path: dist/

      - name: -> publish
        run: just publish
